package com.iut.banque.test.selenium;// Generated by Selenium IDE
import org.junit.Ignore;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import static org.junit.Assert.assertTrue;

import java.util.*;

@Ignore
public class TestConnectionLoginOk {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "src\\main\\resources\\chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testConnectionLoginOk() {
    driver.get("http://localhost:8082/_00_ASBank2023/");
    driver.manage().window().setSize(new Dimension(1552, 840));
    driver.findElement(By.linkText("Accéder à la banque")).click();
    driver.findElement(By.id("controller_Connect_login_action_userCde")).click();
    driver.findElement(By.id("controller_Connect_login_action_userCde")).sendKeys("admin");
    driver.findElement(By.id("controller_Connect_login_action_userPwd")).click();
    driver.findElement(By.id("controller_Connect_login_action_userPwd")).sendKeys("admin");
    driver.findElement(By.id("controller_Connect_login_action_submit")).click();

    assertTrue(driver.getTitle().contains("Tableau de bord - Gestionnaire"));
  }
}
